server:
  port: 8080
  servlet:
    context-path: /education
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/education_system"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/education-service

idp:
  url: http://localhost:8180
  client-id: education_app
  client-secret: VzYF8s3JFejTwDFTE0df2GH5YuF4AXNA

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG