server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/edu_app"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/security-keycloak

idp:
  url: http://localhost:8180
  client-id: security_app
  client-secret: zDIbHoUdxlP1XzBIzGDB2MKxY9fM2FcD

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG